// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGXUpNg-vmpUIkHGnEj3KMqBkQrK_kYzg',
    appId: '1:898179316329:web:a9885fe78b9ca1a74580f8',
    messagingSenderId: '898179316329',
    projectId: 'resdhan-earnings',
    authDomain: 'resdhan-earnings.firebaseapp.com',
    databaseURL: 'https://resdhan-earnings-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resdhan-earnings.appspot.com',
    measurementId: 'G-1PMPE06G25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxcDRvH0nOExp0zQA6wkqZxkAiLVJ8Rk',
    appId: '1:898179316329:android:68592c23522aa86f4580f8',
    messagingSenderId: '898179316329',
    projectId: 'resdhan-earnings',
    databaseURL: 'https://resdhan-earnings-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resdhan-earnings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxusQk0AhRTdkY6VVg7Cwy4YgnRZ0PHgc',
    appId: '1:898179316329:ios:017cdcc0999480624580f8',
    messagingSenderId: '898179316329',
    projectId: 'resdhan-earnings',
    databaseURL: 'https://resdhan-earnings-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'resdhan-earnings.appspot.com',
    androidClientId: '898179316329-6rj2bknrv4dnh8rrp50cdtqoqcptgrv1.apps.googleusercontent.com',
    iosClientId: '898179316329-td2ocviorravee4go1ksdsifpsqru35b.apps.googleusercontent.com',
    iosBundleId: 'airdrops.nocorps.xyz',
  );
}